# Generated by Django 3.1.6 on 2021-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0028_auto_20210427_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='pedido',
        ),
    ]
