# Generated by Django 3.1.6 on 2021-04-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0019_pedido_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Loja',
        ),
    ]
