# Generated by Django 3.2.1 on 2021-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='realizado em %d/%m/%Y'),
        ),
    ]
