# Generated by Django 3.1.6 on 2021-04-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0014_auto_20210423_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='pedido',
        ),
    ]
