# Generated by Django 3.1.6 on 2021-04-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0016_pedido_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='component.produto1'),
            preserve_default=False,
        ),
    ]
