# Generated by Django 3.1.6 on 2021-04-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0017_auto_20210423_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='teste',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='component.produto'),
            preserve_default=False,
        ),
    ]
