# Generated by Django 3.1.6 on 2021-04-26 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0018_auto_20210423_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Loja',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=20),
        ),
    ]
